server:
  port: ${port:8082}
my:
  nacos:
    discovery:
      serverAddr: localhost:25544
      username: nacos
      password: nacos
      namespace: prod
  application:
    name: res-food
user:
  name: 123
  password: asd

ourstorage:
  localspace: H:\codes


