server:
  port: ${port:8082}
my:
  nacos:
    discovery:
      serverAddr: 127.0.0.1:25544
      username: nacos
      password: nacos
      namespace: prod
  application:
    name: res-food
user:
  name: 123
  password: asd

our-storage:
  local-space: H:\our_nacos_files

