server:
  port: ${port:8082}
my:
  nacos:
    discovery:
      serverAddr: 192.168.1.200:25544
      username: nacos
      password: nacos
      namespace: prod
  application:
    name: res-food
user:
  name: 123
  password: asd

our-storage:
  local-space: D:\demo


